{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:45.947Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:45.950Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:47.990Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:47.992Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:48.003Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.035Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.037Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:50.051Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.087Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.089Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:52.103Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.051Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.052Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:55.066Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:26:58.873Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:12.717Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:14.842Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:16.972Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:19.794Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'MongoNetworkError',\n  errorLabels: [ 'TransientTransactionError' ],\n  [Symbol(mongoErrorContextSymbol)]: {} } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (C:\\Users\\poovarasanv\\IdeaProjects\\Border\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","timestamp":"2019-02-06T07:29:23.450Z"}
